# Site settings
title: Design Portfolio
email: mario@datamaw.com
description: > # this means to ignore newlines until "baseurl:"
  Testing jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: noncasus
github_username:  noncasus

permalink:  /:categories/:title

links:
  - title:  about
    url:    /about
  - title:  work
    url:    /work
  - title:  articles
    url:    /articles
  - title:  hire-me
    url:    /hire-me

# Build settings
markdown: kramdown
